version: '3.8'

services:
  hfdlsp:
    build:
      context: ./src
    command: gunicorn HFDLSP.wsgi:application --bind 0.0.0.0:8080
    container_name: hfdlsp
    env_file:
      - ./src/.env

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - hfdlsp
