version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y pip
            pip install --upgrade pip
            pip install flake8==6.0.0
            pip install -r src/requirements.txt
      - run:
          name: Run linter
          command: |
            flake8 --ignore=E501,F401 src/.
      - run:
          name: Run tests
          command: |
            python src/manage.py test

  build_and_push_image:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t trenchesai/hfdlsp:$TAG src
            docker tag trenchesai/hfdlsp:$TAG trenchesai/hfdlsp:latest

      - run:
          name: Push Docker image to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push  trenchesai/hfdlsp:latest trenchesai/hfdlsp:$TAG

workflows:
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - release
      - build_and_push_image:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release
